server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ls-1cbbba9eb8cd1fd863325905431688dd6fa82dba.cfk8mckqasu6.ap-northeast-2.rds.amazonaws.com/dorering
    username: dbmasteruser
    password: A=SWadBq3MuL_V:It7>maC{y?3:J+17u
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        
jwt:
  key: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9
  time: 86400000
  secret: eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0

elevenlabs-api:
  key: "2fae9a043baf5a1c42b9d7697c20e8ff"

image:
  #WebConfig에 세팅
  add-resource-location: file:///C:/Users/USER/Desktop/Project/DoRing/src/main/resources/static/
  add-resource-handler: /images/**
  # 파일 업로드 경로
  image-dir: C:/Users/USER/Desktop/Project/DoRing/src/main/resources/static/images/
  image-url: http://dorering.com:8001/images/